[FEAT] - Add text view
Cosmo-Coleus/Cosmo pull request #3
Opened 2024-07-08 20:53 UTC by alex-robert-fr

# Résumé des modifications SOURCES
- Passage en mode RAW du terminal
- Affichage d'une ligne de commande avec `:`
- Possibilité de quitter l'IDE à avec `:q`

2024-07-09 15:19 UTC, Mihawka reviewed
TODO

2024-07-09 15:19 UTC, Mihawka commented on src/main.rs
> +    let _ = run_app(&mut terminal, &mut app);
```suggestion
    run_app(&mut terminal, &mut app)?;
```

2024-07-09 15:19 UTC, Mihawka commented on src/app.rs
> +    commande_buffer: String
```suggestion
    command_buffer: String
```

2024-07-10 15:03 UTC, Mihawka requested changes

2024-07-10 15:03 UTC, Mihawka commented on src/app/editor_modes.rs
> +    match key {
```
warning: you seem to be trying to use `match` for an equality check. Consider using `if`
  --> src/app/editor_modes.rs:17:5
   |
17 | /     match key {
18 | |         KeyCode::Esc => app.input_mode = InputMode::Normal,
19 | |         _ => {}
20 | |     }
   | |_____^ help: try: `if key == KeyCode::Esc { app.input_mode = InputMode::Normal }`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_match
   = note: `#[warn(clippy::single_match)]` on by default
```

2024-07-10 15:03 UTC, Mihawka commented on Cargo.lock
Ajouter ce fichier au gitignore !

2024-07-10 15:03 UTC, Mihawka commented on src/main.rs
> +fn core_init() -> Result<()> {
core_init. init ne semble pas être le terme le plus approprié car cette fonction ne gère pas que l'initialisation.

2024-07-10 15:35 UTC, alex-robert-fr commented on src/app/editor_modes.rs
> +    match key {
Oui je l'ai vu passer, je vais modifier ca

2024-07-10 15:37 UTC, alex-robert-fr commented on src/main.rs
> +fn core_init() -> Result<()> {
Elle gère quoi d'autre que l'initialisation ? 🤔

2024-07-10 15:54 UTC, Mihawka approved these changes

2024-07-10 15:55 UTC, merged